# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name
    steps:
      - checkout
      - run:
          command: .github/ci.sh
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
