# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
        environment:
          KERL_BUILD_BACKEND: git
          MAKEFLAGS: -j4
    steps:
      - checkout 
      - run:
          command: sudo apt-get update -y && sudo apt-get install -y libncurses5-dev
      - run:
          command: curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
      - run:
          command: chmod +x kerl && sudo mv kerl /usr/bin/ && mkdir ~/installs
      - run:
          command: kerl update releases && kerl build 25.0 ~/installs/      
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
